version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://chaud:teste@db:5432/property_db
    depends_on:
      - db
    volumes:
      - ./src:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: chaud
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: property_db
    ports:
      - "5432:5432"